#!/usr/bin/env node
const fs = require('node:fs/promises');
const path = require('node:path');

function readArg(flag) {
  const index = process.argv.indexOf(flag);
  if (index === -1) return undefined;
  return process.argv[index + 1];
}

async function main() {
  const svgPath = readArg('--svg');
  const pngPath = readArg('--png');
  const encodedPath = readArg('--encoded');

  if (!svgPath || !pngPath) {
    throw new Error('Usage: deploy-wiki.js --svg <file.svg> --png <file.png> [--encoded <file>]');
  }

  await fs.access(svgPath);
  await fs.access(pngPath);
  if (encodedPath) {
    await fs.access(encodedPath);
  }

  const summaryPath = path.join(path.dirname(svgPath), 'deployment-summary.md');
  const body = [
    '# PlantUML Wiki Deployment Summary',
    '',
    `- SVG artifact: ${path.basename(svgPath)}`,
    `- PNG artifact: ${path.basename(pngPath)}`,
    encodedPath ? `- Encoded source: ${path.basename(encodedPath)}` : '- Encoded source: n/a',
    '',
    'This summary is generated by pipeline automation and can be published to Azure DevOps Wiki.'
  ].join('\n');

  await fs.writeFile(summaryPath, body, 'utf-8');
  console.log(`Deployment package prepared: ${summaryPath}`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
